config/routes.rb
Ev4App::Application.routes.draw do

  resources :vouchers

  resources :plans

  resources :voucher_accounts

  resources :users

  resources :clients

  get "client/new"

  get "pages/home"

  get "pages/contact"

  resources :organizations

end

app/models/voucher_account.rb
class VoucherAccount < ActiveRecord::Base
  has_many :users
end

app/controllers/voucher_accounts_controller.rb
class VoucherAccountsController < ApplicationController
  # GET /voucher_accounts
  # GET /voucher_accounts.json
  def index
    @voucher_accounts = VoucherAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @voucher_accounts }
      format.xml { render :xml => @voucher_accounts }
    end
  end

  # GET /voucher_accounts/1
  # GET /voucher_accounts/1.json
  def show
    @voucher_account = VoucherAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @voucher_account }
    end
  end

  # GET /voucher_accounts/new
  # GET /voucher_accounts/new.json
  def new
    @voucher_account = VoucherAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @voucher_account }
    end
  end

  # GET /voucher_accounts/1/edit
  def edit
    @voucher_account = VoucherAccount.find(params[:id])
  end

  # POST /voucher_accounts
  # POST /voucher_accounts.json
  def create
    @voucher_account = VoucherAccount.new(params[:voucher_account])

    respond_to do |format|
      if @voucher_account.save
        format.html { redirect_to @voucher_account, :notice => 'Voucher account was successfully created.' }
        format.json { render :json => @voucher_account, :status => :created, :location => @voucher_account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @voucher_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /voucher_accounts/1
  # PUT /voucher_accounts/1.json
  def update
    @voucher_account = VoucherAccount.find(params[:id])

    respond_to do |format|
      if @voucher_account.update_attributes(params[:voucher_account])
        format.html { redirect_to @voucher_account, :notice => 'Voucher account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @voucher_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /voucher_accounts/1
  # DELETE /voucher_accounts/1.json
  def destroy
    @voucher_account = VoucherAccount.find(params[:id])
    @voucher_account.destroy

    respond_to do |format|
      format.html { redirect_to voucher_accounts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/voucher_accounts_helper.rb
module VoucherAccountsHelper
end

app/views/voucher_accounts/_form.html.erb
<%= form_for(@voucher_account) do |f| %>
  <% if @voucher_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voucher_account.errors.count, "error") %> prohibited this voucher_account from being saved:</h2>

      <ul>
      <% @voucher_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :balence %><br />
    <%= f.number_field :balence %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voucher_accounts/edit.html.erb
<h1>Editing voucher_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @voucher_account %> |
<%= link_to 'Back', voucher_accounts_path %>

app/views/voucher_accounts/index.html.erb
<h1>Listing voucher_accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Balence</th>
    <th>Currency</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @voucher_accounts.each do |voucher_account| %>
  <tr>
    <td><%= voucher_account.name %></td>
    <td><%= voucher_account.balence %></td>
    <td><%= voucher_account.currency %></td>
    <td><%= link_to 'Show', voucher_account %></td>
    <td><%= link_to 'Edit', edit_voucher_account_path(voucher_account) %></td>
    <td><%= link_to 'Destroy', voucher_account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Voucher account', new_voucher_account_path %>

app/views/voucher_accounts/new.html.erb
<h1>New voucher_account</h1>

<%= render 'form' %>

<%= link_to 'Back', voucher_accounts_path %>

app/views/voucher_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @voucher_account.name %>
</p>

<p>
  <b>Balence:</b>
  <%= @voucher_account.balence %>
</p>

<p>
  <b>Currency:</b>
  <%= @voucher_account.currency %>
</p>


<%= link_to 'Edit', edit_voucher_account_path(@voucher_account) %> |
<%= link_to 'Back', voucher_accounts_path %>