config/routes.rb
Ev4App::Application.routes.draw do

  resources :vouchers

  resources :plans

  resources :voucher_accounts

  resources :users

  resources :clients

  get "client/new"

  get "pages/home"

  get "pages/contact"

  resources :organizations

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :vouchers
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @plans }
      format.xml { render :xml => @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, :notice => 'Plan was successfully created.' }
        format.json { render :json => @plan, :status => :created, :location => @plan }
      else
        format.html { render :action => "new" }
        format.json { render :json => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, :notice => 'Plan was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :ok }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :disbursement_date %><br />
    <%= f.datetime_select :disbursement_date %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br />
    <%= f.datetime_select :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :credit %><br />
    <%= f.number_field :credit %>
  </div>
  <div class="field">
    <%= f.label :ratio %><br />
    <%= f.number_field :ratio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Disbursement date</th>
    <th>Expiration date</th>
    <th>Credit</th>
    <th>Ratio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plans.each do |plan| %>
  <tr>
    <td><%= plan.name %></td>
    <td><%= plan.disbursement_date %></td>
    <td><%= plan.expiration_date %></td>
    <td><%= plan.credit %></td>
    <td><%= plan.ratio %></td>
    <td><%= link_to 'Show', plan %></td>
    <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
    <td><%= link_to 'Destroy', plan, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plan.name %>
</p>

<p>
  <b>Disbursement date:</b>
  <%= @plan.disbursement_date %>
</p>

<p>
  <b>Expiration date:</b>
  <%= @plan.expiration_date %>
</p>

<p>
  <b>Credit:</b>
  <%= @plan.credit %>
</p>

<p>
  <b>Ratio:</b>
  <%= @plan.ratio %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>